### ISSUE TITLE
cannot parse package.json

### ISSUE THREAD

**Issue by jamesarosen** [billybonks/ember-cli-stylelint#122]
I'm getting an exception when trying to run stylelint in an ember project. A [search for `A-PRZcf-ntqry`](https://www.google.com/search?q=A-PRZcf-ntqry) turns up a bunch of issues about babel compilation. I don't yet know why that's relevant here. It's possible that some ember-cli dependency is causing stylelint to invoke babel when it shouldn't be.

### Versions
```
"ember-cli-stylelint": "^2.1.0",
"stylelint": "^8.3.1",
"stylelint-order": "^0.8.0"
```

### Backtrace
```
$ npm run lint:style

> @my-org/my-project@1.0.0 lint:style /Users/me/Code/my-project
> stylelint 'addon/styles/**/*.scss'


/Users/me/Code/my-project/node_modules/stylelint/node_modules/load-json-file/node_modules/parse-json/index.js:31
		throw jsonErr;
		^
JSONError: Cannot parse /[\u001B\u009B][[\]()#;?]*(?:(?:(?:[a-zA-Z\d]*(?:;[a-zA-Z\d]*)*)?\u0007)|(?:(?:\d{1,4}(?:;\d{0,4})*)?[\dA-PRZcf-ntqry=><~]))/g in node_modules/stylelint/package.json
    at module.exports.err (/Users/me/Code/my-project/node_modules/stylelint/node_modules/load-json-file/node_modules/parse-json/index.js:26:19)
    at parse (/Users/me/Code/my-project/node_modules/stylelint/node_modules/load-json-file/index.js:8:29)
    at Function.module.exports.sync.fp [as sync] (/Users/me/Code/my-project/node_modules/stylelint/node_modules/load-json-file/index.js:11:29)
    at Function.module.exports.sync (/Users/me/Code/my-project/node_modules/stylelint/node_modules/read-pkg/index.js:40:25)
    at Function.module.exports.sync.opts [as sync] (/Users/me/Code/my-project/node_modules/stylelint/node_modules/read-pkg-up/index.js:23:16)
    at module.exports (/Users/me/Code/my-project/node_modules/stylelint/node_modules/meow/index.js:26:18)
    at Object.<anonymous> (/Users/me/Code/my-project/node_modules/stylelint/lib/cli.js:336:27)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

**Comment by aklkv** [comment]
@jamesarosen you need to supply directory and file extension e.g. `stylelint 'app/**/*.scss'`

**Comment by jamesarosen** [comment]
My description has the same argument you suggest, so I don't think that was it.

But I can no longer reproduce this. I'll close it and reopen if it crops up again.
