### ISSUE TITLE
Incompatible with Octane

### ISSUE THREAD

**Issue by rwwagner90** [billybonks/ember-cli-stylelint#162]
I am not sure what to do to make it work with Octane, but wanted to at least drop the stack trace here.

```
  - stack: TypeError: Funnel: Expected Broccoli node, got null for inputNodes[0]
    at Funnel.Plugin (/Users/rwwagner/shipshape/shipshape.io/node_modules/broccoli-plugin/index.js:23:13)
    at new Funnel (/Users/rwwagner/shipshape/shipshape.io/node_modules/ember-cli-stylelint/node_modules/broccoli-funnel/index.js:58:10)
    at Class.<anonymous> (/Users/rwwagner/shipshape/shipshape.io/node_modules/ember-cli-stylelint/index.js:67:38)
    at Array.map (<anonymous>:null:null)
    at Class.lintTree (/Users/rwwagner/shipshape/shipshape.io/node_modules/ember-cli-stylelint/index.js:66:31)
    at addons.reduce (/Users/rwwagner/shipshape/shipshape.io/node_modules/ember-cli/lib/utilities/lint-addons-by-type.js:6:23)
    at Array.reduce (<anonymous>:null:null)
    at lintAddonsByType (/Users/rwwagner/shipshape/shipshape.io/node_modules/ember-cli/lib/utilities/lint-addons-by-type.js:4:17)
    at EmberApp.addonLintTree (/Users/rwwagner/shipshape/shipshape.io/node_modules/ember-cli/lib/broccoli/ember-app.js:898:18)
    at EmberApp.getLintTests (/Users/rwwagner/shipshape/shipshape.io/node_modules/ember-cli/lib/broccoli/ember-app.js:1423:28)
    at EmberApp.getTests (/Users/rwwagner/shipshape/shipshape.io/node_modules/ember-cli/lib/broccoli/ember-app.js:1337:28)
    at EmberApp.toArray (/Users/rwwagner/shipshape/shipshape.io/node_modules/ember-cli/lib/broccoli/ember-app.js:1644:12)
    at EmberApp.toTree (/Users/rwwagner/shipshape/shipshape.io/node_modules/ember-cli/lib/broccoli/ember-app.js:1775:36)
    at module.exports (/Users/rwwagner/shipshape/shipshape.io/ember-cli-build.js:130:14)
    at Builder.readBuildFile (/Users/rwwagner/shipshape/shipshape.io/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/rwwagner/shipshape/shipshape.io/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/Users/rwwagner/shipshape/shipshape.io/node_modules/ember-cli/lib/models/builder.js:32:10)
    at ServeTask.run (/Users/rwwagner/shipshape/shipshape.io/node_modules/ember-cli/lib/tasks/serve.js:45:55)
    at Promise.resolve.then (/Users/rwwagner/shipshape/shipshape.io/node_modules/ember-cli/lib/models/command.js:243:46)
    at tryCatcher (/Users/rwwagner/shipshape/shipshape.io/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/Users/rwwagner/shipshape/shipshape.io/node_modules/rsvp/dist/rsvp.js:495:31)
    at /Users/rwwagner/shipshape/shipshape.io/node_modules/rsvp/dist/rsvp.js:559:14
    at flush (/Users/rwwagner/shipshape/shipshape.io/node_modules/rsvp/dist/rsvp.js:2402:5)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)
```

**Comment by billybonks** [comment]
thanks i havent tried `octane`, though i use most features packaged with octane will take a look into this sorry for the late reply

**Comment by billybonks** [comment]
Does this work for you now @rwwagner90 ?

**Comment by rwwagner90** [comment]
I think it's a MU issue, not Octane

**Comment by billybonks** [comment]
That could be I'll test it on mu :) thanks

**Comment by billybonks** [comment]
closing this for now open if you notice anything again thanks

**Comment by rwwagner90** [comment]
Should be fine since MU is dead 😃
