### ISSUE TITLE
Outdated version of stylelint

### ISSUE THREAD

**Issue by boydkr** [billybonks/ember-cli-stylelint#312]
The version of stylelint pulled in through this add-on is outdated and conflicts with other addons that include stylelint, causing warning messages in CI builds:

```
Undefined rule unicode-bom
Error: Undefined rule unicode-bom
    at module.exports (/home/circleci/firestorm/node_modules/broccoli-stylelint/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at Object.keys.forEach.ruleName (/home/circleci/firestorm/node_modules/broccoli-stylelint/node_modules/stylelint/lib/augmentConfig.js:325:13)
    at Array.forEach (<anonymous>)
    at normalizeAllRuleSettings (/home/circleci/firestorm/node_modules/broccoli-stylelint/node_modules/stylelint/lib/augmentConfig.js:318:29)
    at augmentConfigBasic.then.then.then.augmentedConfig (/home/circleci/firestorm/node_modules/broccoli-stylelint/node_modules/stylelint/lib/augmentConfig.js:94:14)
```

Requires a new version of `broccoli-stylelint`

**Comment by billybonks** [comment]
Hi, sorry for the delay. I have updated the packages :). use 4.0.0

**Comment by billybonks** [comment]
@boydkr everything good now?

**Comment by boydkr** [comment]
Yes, thanks!
