### ISSUE TITLE
"Something went wrong running stylelint" during normal ember build.

### ISSUE THREAD

**Issue by kitsunde** [billybonks/ember-cli-stylelint#43]
It seems like stylelint is being called during `ember build`.

```bash
$ ember build
WARNING: Node v7.2.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js.
⠙ Building======= Something went wrong running stylelint =======
TypeError: Cannot read property 'forEach' of null
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/stylelint/dist/rules/media-feature-name-no-vendor-prefix/index.js:22:14
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:302:28
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:148:26
    at Root.each (/Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:114:22)
    at Root.walk (/Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:147:21)
    at Root.walkAtRules (/Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:300:25)
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/stylelint/dist/rules/media-feature-name-no-vendor-prefix/index.js:15:10
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/stylelint/dist/lintSource.js:110:52
TypeError: Cannot read property 'forEach' of null
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/stylelint/dist/rules/media-feature-name-no-vendor-prefix/index.js:22:14
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:302:28
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:148:26
    at Root.each (/Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:114:22)
    at Root.walk (/Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:147:21)
    at Root.walkAtRules (/Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:300:25)
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/stylelint/dist/rules/media-feature-name-no-vendor-prefix/index.js:15:10
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/stylelint/dist/lintSource.js:110:52
⠴ Building======= Something went wrong running stylelint =======
TypeError: Cannot read property 'forEach' of null
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/stylelint/dist/rules/media-feature-name-no-vendor-prefix/index.js:22:14
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:302:28
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:148:26
    at Root.each (/Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:114:22)
    at Root.walk (/Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:147:21)
    at Root.walkAtRules (/Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:300:25)
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/stylelint/dist/rules/media-feature-name-no-vendor-prefix/index.js:15:10
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/stylelint/dist/lintSource.js:110:52
TypeError: Cannot read property 'forEach' of null
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/stylelint/dist/rules/media-feature-name-no-vendor-prefix/index.js:22:14
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:302:28
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:148:26
    at Root.each (/Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:114:22)
    at Root.walk (/Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:147:21)
    at Root.walkAtRules (/Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:300:25)
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/stylelint/dist/rules/media-feature-name-no-vendor-prefix/index.js:15:10
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/stylelint/dist/lintSource.js:110:52
cleaning up...
Built project successfully. Stored in "dist/".
```

The build does seem to complete without issue. I'm uncertain what the cause is.

**Comment by billybonks** [comment]
Hey, it does run when you run ember build, as `ember serve` basically uses `ember build`.  does this error occur when you run `ember serve` ? i am assuming not

**Comment by kitsunde** [comment]
Yeah it also runs on `ember s`:

```
$ ember s
WARNING: Node v7.2.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js.
Livereload server on http://localhost:49154
Serving on http://localhost:4200/
======= Something went wrong running stylelint =======
TypeError: Cannot read property 'forEach' of null
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/stylelint/dist/rules/media-feature-name-no-vendor-prefix/index.js:22:14
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:302:28
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:148:26
    at Root.each (/Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:114:22)
    at Root.walk (/Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:147:21)
    at Root.walkAtRules (/Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:300:25)
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/stylelint/dist/rules/media-feature-name-no-vendor-prefix/index.js:15:10
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/stylelint/dist/lintSource.js:110:52
TypeError: Cannot read property 'forEach' of null
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/stylelint/dist/rules/media-feature-name-no-vendor-prefix/index.js:22:14
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:302:28
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:148:26
    at Root.each (/Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:114:22)
    at Root.walk (/Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:147:21)
    at Root.walkAtRules (/Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:300:25)
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/stylelint/dist/rules/media-feature-name-no-vendor-prefix/index.js:15:10
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/stylelint/dist/lintSource.js:110:52
======= Something went wrong running stylelint =======
TypeError: Cannot read property 'forEach' of null
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/stylelint/dist/rules/media-feature-name-no-vendor-prefix/index.js:22:14
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:302:28
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:148:26
    at Root.each (/Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:114:22)
    at Root.walk (/Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:147:21)
    at Root.walkAtRules (/Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:300:25)
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/stylelint/dist/rules/media-feature-name-no-vendor-prefix/index.js:15:10
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/stylelint/dist/lintSource.js:110:52
TypeError: Cannot read property 'forEach' of null
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/stylelint/dist/rules/media-feature-name-no-vendor-prefix/index.js:22:14
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:302:28
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:148:26
    at Root.each (/Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:114:22)
    at Root.walk (/Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:147:21)
    at Root.walkAtRules (/Users/kitsunde/Development/mediapop/src/frontend/node_modules/postcss/lib/container.js:300:25)
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/stylelint/dist/rules/media-feature-name-no-vendor-prefix/index.js:15:10
    at /Users/kitsunde/Development/mediapop/src/frontend/node_modules/stylelint/dist/lintSource.js:110:52
```

**Comment by billybonks** [comment]
@kitsunde i think there is a problem with your linting rules of some sort, can you link me your `.stylerc` ?

**Comment by kitsunde** [comment]
I should point out that it runs just fine during `ember test`.

```
{
  "rules": {
    "color-no-invalid-hex": true,
    "color-hex-case": "lower",
    "function-comma-space-after": "always-single-line",
    "function-comma-space-before": "never",
    "function-max-empty-lines": 0,
    "function-name-case": "lower",
    "function-parentheses-space-inside": "never-single-line",
    "function-url-scheme-whitelist": [
      "http",
      "https",
      "data"
    ],
    "number-no-trailing-zeros": true,
    "string-no-newline": true,
    "length-zero-no-unit": true,
    "unit-case": "lower",
    "unit-no-unknown": true,
    "value-keyword-case": "lower",
    "value-no-vendor-prefix": true,
    "value-list-comma-space-after": "always",
    "value-list-comma-space-before": "never",
    "value-list-max-empty-lines": 0,
    "shorthand-property-no-redundant-values": true,
    "keyframe-declaration-no-important": true,
    "declaration-bang-space-before": "always",
    "declaration-colon-space-after": "always",
    "declaration-colon-space-before": "never",
    "declaration-block-single-line-max-declarations": 1,
    "declaration-block-trailing-semicolon": "always",
    "block-closing-brace-empty-line-before": "never",
    "block-closing-brace-newline-after": "always",
    "block-closing-brace-newline-before": "always",
    "block-closing-brace-space-after": "never-single-line",
    "block-closing-brace-space-before": "never-single-line",
    "block-no-empty": true,
    "block-no-single-line": true,
    "block-opening-brace-newline-after": "always",
    "block-opening-brace-space-after": "never-single-line",
    "block-opening-brace-space-before": "always",
    "selector-attribute-brackets-space-inside": "never",
    "selector-attribute-operator-space-after": "never",
    "selector-attribute-operator-space-before": "never",
    "selector-combinator-space-after": "always",
    "selector-combinator-space-before": "always",
    "selector-descendant-combinator-no-non-space": true,
    "selector-no-empty": true,
    "selector-no-vendor-prefix": true,
    "selector-pseudo-class-case": "lower",
    "selector-pseudo-class-no-unknown": true,
    "selector-pseudo-class-parentheses-space-inside": "never",
    "selector-pseudo-element-case": "lower",
    "selector-pseudo-element-no-unknown": true,
    "selector-root-no-composition": true,
    "selector-type-case": "lower",
    "selector-type-no-unknown": true,
    "selector-max-empty-lines": 0,
    "selector-list-comma-newline-before": "never-multi-line",
    "selector-list-comma-space-after": "always-single-line",
    "selector-list-comma-space-before": "never",
    "media-feature-colon-space-after": "always",
    "media-feature-colon-space-before": "never",
    "media-feature-name-case": "lower",
    "media-feature-name-no-vendor-prefix": true,
    "media-feature-no-missing-punctuation": true,
    "media-feature-parentheses-space-inside": "never",
    "media-feature-range-operator-space-after": "always",
    "media-feature-range-operator-space-before": "always",
    "media-query-list-comma-space-after": "always-single-line",
    "media-query-list-comma-space-before": "never",
    "at-rule-name-case": "lower",
    "at-rule-name-space-after": "always",
    "at-rule-no-unknown": true,
    "at-rule-no-vendor-prefix": true,
    "at-rule-semicolon-newline-after": "always",
    "comment-no-empty": true,
    "comment-whitespace-inside": "always",
    "indentation": 2,
    "max-empty-lines": 1,
    "max-line-length": 120,
    "no-empty-source": true,
    "no-extra-semicolons": true,
    "no-missing-end-of-source-newline": true,
    "no-unknown-animations": true
  }
}
```

**Comment by billybonks** [comment]
hey i tried with your stylesheet to no success is this problem still affecting you ?
